# Docker file specifying  MITRE SSL certificates for a Full Stack CNAB invocation image
FROM ubuntu:latest

ARG BUNDLE_DIR
ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND=noninteractive

COPY ./mongo-init.js ${BUNDLE_DIR}/mongo-init.js
COPY ./.cnab/app/porter.yaml ${BUNDLE_DIR}/porter.yaml
COPY ./docker-compose-porter.yml ${BUNDLE_DIR}/docker-compose-porter.yml
COPY ./.env ${BUNDLE_DIR}/.env
