version: '3.6'
services:
  keycloak:
    container_name: rems_dev_keycloak
    # command: ["-Djboss.http.port=8180"]
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - rems_dev_keycloak-data:/opt/jboss/keycloak/standalone/data/
      - '../test-ehr/src/main/resources/ClientFhirServerRealm.json:/resources/ClientFhirServerRealm.json'
    build:
      context: ../test-ehr
      dockerfile: Dockerfile.keycloak

  test-ehr:
    container_name: rems_dev_test-ehr
    ports:
      - '8080:8080'
      - "8081:8081"
    build:
      context: ../test-ehr
      dockerfile: Dockerfile.dev
    environment:
      - oauth_token=http://host.docker.internal:8180/auth/realms/ClientFhirServer/protocol/openid-connect/token
    volumes:
      - rems_dev_test-ehr-sync:/test-ehr:nocopy #  nocopy is important
      - rems_dev_test-ehr-gradle:/test-ehr/.gradle
      - rems_dev_test-ehr-bin:/test-ehr/bin
      - rems_dev_test-ehr-build:/test-ehr/build
      - rems_dev_test-ehr-target:/test-ehr/target
      - rems_dev_test-ehr-logs:/test-ehr/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pims_remsadmin_mongo:
    image: mongo
    container_name: rems_dev_pims-remsadmin-mongo
    ports:
      - '27017:27017' 
    environment:
      MONGO_INITDB_ROOT_USERNAME: rems-admin-pims-root
      MONGO_INITDB_ROOT_PASSWORD: rems-admin-pims-password
    volumes:
      - rems_dev_pims_remsadmin_mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  crd-request-generator:
    build:
      context: ../crd-request-generator
      dockerfile: Dockerfile.dev
    container_name: rems_dev_crd-request-generator
    environment:
      - REACT_APP_REMS_CONFIG=true
    ports:
      - "3000:3000" 
      - "3001:3001"
    volumes:
      - rems_dev_crd-request-generator-sync:/home/node/app/crd-request-generator:nocopy #  nocopy is important
      - rems_dev_crd-request-generator-nodeModules:/home/node/app/crd-request-generator/node_modules
      - rems_dev_crd-request-generator-databaseData:/home/node/app/crd-request-generator/databaseData
      - rems_dev_crd-request-generator-build:/home/node/app/crd-request-generator/build
      - rems_dev_crd-request-generator-logs:/home/node/app/crd-request-generator/logs

  dtr:
    build:
      context: ../dtr
      dockerfile: Dockerfile.dev
    container_name: rems_dev_dtr
    ports:
      - "3005:3005"
      - "3006:3006"
    volumes:
      - rems_dev_dtr-sync:/home/node/app/dtr:nocopy #  nocopy is important
      - rems_dev_dtr-nodeModules:/home/node/app/dtr/node_modules
      - rems_dev_dtr-databaseData:/home/node/app/dtr/databaseData
      - rems_dev_dtr-logs:/home/node/app/dtr/logs

  rems-smart-on-fhir:
    build:
      context: ../rems-smart-on-fhir
      dockerfile: Dockerfile.dev
    container_name: rems_dev_rems-smart-on-fhir
    ports:
      - "4040:4040"
      - "4041:4041"
    volumes:
      - rems_dev_rems-smart-on-fhir-sync:/home/node/app/rems-smart-on-fhir:nocopy #  nocopy is important
      - rems_dev_rems-smart-on-fhir-nodeModules:/home/node/app/rems-smart-on-fhir/node_modules
      - rems_dev_rems-smart-on-fhir-logs:/home/node/app/rems-smart-on-fhir/logs

  rems-administrator:
    build:
      context: '.'
      dockerfile: Dockerfile.dev
    container_name: rems_dev_rems-administrator
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      VSAC_API_KEY: ${VSAC_API_KEY}
      MONGO_URL: mongodb://rems-user:pass@pims_remsadmin_mongo:27017
    volumes:
      - rems_dev_rems-sync:/REMS:nocopy #  nocopy is important
      - rems_dev_rems-nodeModules:/REMS/node_modules
      - rems_dev_rems-logs:/REMS/logs

  pims:
    build:
      context: ../pims
      dockerfile: Dockerfile.dev
    container_name: rems_dev_pims
    ports:
      - "5050:5050" 
      - "5051:5051"
    environment:
      REMS_ADMIN_BASE: http://rems-administrator:8090
      MONGO_HOSTNAME: mongodb://pims_remsadmin_mongo:27017/pims
    volumes:
      - rems_dev_pims-sync:/home/node/app/pims:nocopy
      - rems_dev_pims-nodeModules:/home/node/app/pims/node_modules
      - rems_dev_pims-logs:/home/node/app/pims/logs
  

volumes:
  rems_dev_test-ehr-sync:
    external: true
  rems_dev_crd-request-generator-sync:
    external: true
  rems_dev_dtr-sync:
    external: true
  rems_dev_rems-sync:
    external: true
  rems_dev_pims-sync:
    external: true
  rems_dev_rems-smart-on-fhir-sync:
    external: true


  rems_dev_keycloak-data:
  rems_dev_pims_remsadmin_mongo:
  rems_dev_test-ehr-gradle:
  rems_dev_test-ehr-bin:
  rems_dev_test-ehr-build:
  rems_dev_test-ehr-target:
  rems_dev_test-ehr-logs:
  rems_dev_crd-resources-build:
  rems_dev_crd-request-generator-nodeModules:
  rems_dev_crd-request-generator-databaseData:
  rems_dev_crd-request-generator-build:
  rems_dev_crd-request-generator-logs:
  rems_dev_dtr-nodeModules:
  rems_dev_dtr-databaseData:
  rems_dev_dtr-logs:
  rems_dev_pims-logs: 
  rems_dev_pims-nodeModules: 
  rems_dev_rems-nodeModules:
  rems_dev_rems-logs:
  rems_dev_rems-smart-on-fhir-nodeModules:
  rems_dev_rems-smart-on-fhir-logs:

