version: '3.6'
services:
  keycloak:
    container_name: rems_prod_m1_keycloak  
    # command: ["-Djboss.http.port=8180"]
    ports:
      - '8180:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    volumes:
      - rems_prod_m1_keycloak-data:/opt/jboss/keycloak/standalone/data/
    image: codexrems/keycloak-m1:REMSvCurrent

  # Create test-ehr container
  test-ehr: # Name of our service
    container_name: rems_prod_m1_test-ehr
    ports: # Port binding to host from docker container
      - '8080:8080' # Bind port 3000 of host to 3000 of container
    image: codexrems/test-ehr:REMSvCurrent
    environment:
      - DOCKER_PROFILE=true
    extra_hosts:
      - "host.docker.internal:host-gateway"


  # Create crd request generator container
  crd-request-generator: # Name of our service
    image: codexrems/crd-request-generator:REMSvCurrent
    container_name: rems_prod_m1_crd-request-generator
    environment:
      - REACT_APP_REMS_CONFIG=true
    ports: # Port binding to host from docker container
      - "3000:3000" # Bind port 3000 of host to 3000 of container
      - "3001:3001"

  # Create dtr container
  dtr: # Name of our service
    image: codexrems/dtr:REMSvCurrent
    container_name: rems_prod_m1_dtr
    ports: # Port binding to host from docker container
      - "3005:3005" # Bind port 3000 of host to 3000 of container

  rems-smart-on-fhir:
    image: codexrems/rems-smart-on-fhir:REMSvCurrent
    container_name: rems_prod_m1_rems-smart-on-fhir
    ports:
      - "4040:4040"

  # # Create rems container
  rems-administrator: # Name of our service
    image: codexrems/rems-administrator:REMSvCurrent
    container_name: rems_prod_m1_rems
    ports: # Port binding to host from docker container
      - "9015:9015" # Bind port 3000 of host to 3000 of container
    environment:
      VSAC_API_KEY: ${VSAC_API_KEY}
      MONGO_URL: mongodb://rems-user:pass@pims_remsadmin_mongo:27017

  pims_remsadmin_mongo:
    image: mongo
    container_name: rems_prod_m1_pims-remsadmin-mongo
    ports:
      - '27017:27017' 
    environment:
      MONGO_INITDB_ROOT_USERNAME: rems-admin-pims-root
      MONGO_INITDB_ROOT_PASSWORD: rems-admin-pims-password
    volumes:
      - rems_prod_m1_pims_remsadmin_mongo:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  pims:
    image: codexrems/pims:REMSvCurrent
    container_name: rems_prod_m1_pims
    environment:
      REMS_ADMIN_BASE: http://rems-administrator:8090
      MONGO_HOSTNAME: mongodb://pims_remsadmin_mongo:27017/pims
    ports:
      - "5050:5050" 
      - "5051:5051"




volumes:
  rems_prod_m1_keycloak-data:
  rems_prod_m1_pims_remsadmin_mongo:

